
import java.util.ArrayList;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author maxen
 */
public class FenetreQuiz extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FenetreQuiz.class.getName());

    private ArrayList<Question> listeQuestions = new ArrayList<>();
    private int indexQuestionCourante = 0;
    private int score = 0;

    /**
     * Creates new form FenetreQuiz
     */
    public FenetreQuiz() {
        initComponents();
        lblScore.setText("Score : " + score);
        //Questions :
        listeQuestions.add(new Question(
                "Quelle est la capitale de la France ?",
                "Lyon", "Paris", "Marseille", "Nice",
                2));

        listeQuestions.add(new Question(
                "Combien font 3 × 3 ?",
                "6", "9", "12", "3",
                2));

        listeQuestions.add(new Question(
                "Quel est l'océan à l'ouest de l'Europe ?",
                "Atlantique", "Arctique", "Indien", "Pacifique",
                1));

        listeQuestions.add(new Question(
                "Quel langage est utilisé avec NetBeans ?",
                "C++", "Java", "Python", "HTML",
                2));

        listeQuestions.add(new Question(
                "Combien y a-t-il de continents ?",
                "4", "5", "6", "7",
                4));

        afficherQuestionCourante();

    }

    private void afficherQuestionCourante() {

        Question q = listeQuestions.get(indexQuestionCourante);

        lblQuestion.setText(q.getIntitule());

        btnRep1.setText(q.getProposition1());
        btnRep2.setText(q.getProposition2());
        btnRep3.setText(q.getProposition3());
        btnRep4.setText(q.getProposition4());

        btnRep1.setEnabled(true);
        btnRep2.setEnabled(true);
        btnRep3.setEnabled(true);
        btnRep4.setEnabled(true);

        lblFeedBack.setVisible(false);
    }

    private void verifierReponse(int numChoisi) {

        Question q = listeQuestions.get(indexQuestionCourante);
        lblFeedBack.setVisible(true);

        if (numChoisi == q.getIndexBonneReponse()) {
            lblFeedBack.setText("Bonne réponse");
            score++;
        } else {
            lblFeedBack.setText("Mauvaise réponse");
        }

        btnRep1.setEnabled(false);
        btnRep2.setEnabled(false);
        btnRep3.setEnabled(false);
        btnRep4.setEnabled(false);

        lblScore.setText("Score : " + score);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblQuestion = new javax.swing.JLabel();
        btnRep1 = new javax.swing.JButton();
        btnRep2 = new javax.swing.JButton();
        btnRep3 = new javax.swing.JButton();
        btnRep4 = new javax.swing.JButton();
        lblFeedBack = new javax.swing.JLabel();
        lblScore = new javax.swing.JLabel();
        btnSuivant = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblQuestion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblQuestion.setText("jLabel1");
        getContentPane().add(lblQuestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, -1, -1));

        btnRep1.setText("jButton1");
        btnRep1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRep1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnRep1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, -1, -1));

        btnRep2.setText("jButton2");
        btnRep2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRep2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnRep2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, -1, -1));

        btnRep3.setText("jButton3");
        btnRep3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRep3ActionPerformed(evt);
            }
        });
        getContentPane().add(btnRep3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, -1, -1));

        btnRep4.setText("jButton4");
        btnRep4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRep4ActionPerformed(evt);
            }
        });
        getContentPane().add(btnRep4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, -1, -1));

        lblFeedBack.setText("jLabel1");
        getContentPane().add(lblFeedBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, -1, -1));

        lblScore.setText("jLabel1");
        getContentPane().add(lblScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btnSuivant.setText("jButton1");
        btnSuivant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuivantActionPerformed(evt);
            }
        });
        getContentPane().add(btnSuivant, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRep1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRep1ActionPerformed
        // TODO add your handling code here:
        verifierReponse(1);
    }//GEN-LAST:event_btnRep1ActionPerformed

    private void btnRep2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRep2ActionPerformed
        // TODO add your handling code here:
        verifierReponse(2);
    }//GEN-LAST:event_btnRep2ActionPerformed

    private void btnRep3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRep3ActionPerformed
        // TODO add your handling code here:
        verifierReponse(3);
    }//GEN-LAST:event_btnRep3ActionPerformed

    private void btnRep4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRep4ActionPerformed
        // TODO add your handling code here:
        verifierReponse(4);
    }//GEN-LAST:event_btnRep4ActionPerformed

    private void btnSuivantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuivantActionPerformed
        // TODO add your handling code here:
        btnSuivant.setText("Suivant");
        indexQuestionCourante ++;
   
    if (indexQuestionCourante < listeQuestions.size()) {

        afficherQuestionCourante();

    } else {

        lblFeedBack.setText("Quiz terminé. Score : " + score + " / " + listeQuestions.size());

        btnSuivant.setEnabled(false);

        btnRep1.setEnabled(false);
        btnRep2.setEnabled(false);
        btnRep3.setEnabled(false);
        btnRep4.setEnabled(false);
        }
    }//GEN-LAST:event_btnSuivantActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FenetreQuiz().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRep1;
    private javax.swing.JButton btnRep2;
    private javax.swing.JButton btnRep3;
    private javax.swing.JButton btnRep4;
    private javax.swing.JButton btnSuivant;
    private javax.swing.JLabel lblFeedBack;
    private javax.swing.JLabel lblQuestion;
    private javax.swing.JLabel lblScore;
    // End of variables declaration//GEN-END:variables
}
