/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author maxen
 */
public class FenetreAccueil extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FenetreAccueil.class.getName());

    /**
     * Creates new form FenetreAccueil
     */
    public FenetreAccueil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        texte_titre = new javax.swing.JLabel();
        bouton_jouer = new javax.swing.JButton();
        bouton_quitter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        texte_titre.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        texte_titre.setText("CADENAS");
        getContentPane().add(texte_titre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        bouton_jouer.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bouton_jouer.setText("Jouer");
        bouton_jouer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouton_jouerActionPerformed(evt);
            }
        });
        getContentPane().add(bouton_jouer, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 154, 91, -1));

        bouton_quitter.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bouton_quitter.setText("Quitter");
        bouton_quitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouton_quitterActionPerformed(evt);
            }
        });
        getContentPane().add(bouton_quitter, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 203, 90, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bouton_jouerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton_jouerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bouton_jouerActionPerformed

    private void bouton_quitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton_quitterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bouton_quitterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FenetreAccueil().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bouton_jouer;
    private javax.swing.JButton bouton_quitter;
    private javax.swing.JLabel texte_titre;
    // End of variables declaration//GEN-END:variables
}
